///////////////////////////////////////////////////////////
//  Attendee.cs
//  Implementation of the Class Attendee
//  Generated by Enterprise Architect
//  Created on:      2014/08/05 9:05:17
//  Original author: shiba
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Windows.Forms;
namespace AttendeeAllocator
{
    /// <summary>
    /// 参加者情報
    /// </summary>
    [Serializable]
    public class AttendeeInfo : CsvData
    {


        public AttendeeInfo()
        {

        }


		~AttendeeInfo(){

		}

		public virtual void Dispose(){

		}
        //------------------------
        //Method
        //------------------------
        /// <summary>
        /// データの有効性確認
        /// </summary>
        /// <returns></returns>
        public override bool CheckComformance()
        {
            if (_rows == null)
            {
                return false;
            }
            bool result = true;
            //データが空ならNG
            if (_rows.Count == 0)
            {
                result = false;
            }


            return result;
        }

        public void ChangeColorForLayoutItem(DataGridView dgv)
        {

        }

        //------------------------
        //Properties
        //------------------------


	}//end Attendee

}//end namespace SWESTAttendeeAllocator