///////////////////////////////////////////////////////////
//  Compartment.cs
//  Implementation of the Class Compartment
//  Generated by Enterprise Architect
//  Created on:      2014/08/05 9:05:17
//  Original author: shiba
///////////////////////////////////////////////////////////




using System;
namespace AttendeeAllocator
{
    [Serializable]
    public class CompartmentInfo : CsvData
    {

        /// <summary>
        /// 区画の固定項目定義
        /// </summary>
        string[] COMPARTMENT_DATA_COLUMN = new string[] { "名称","人数","優先グループ","X","Y" };
        public enum COLUM_POS
        {
            Name = 0,
            Max = 1,
            PriorityGroup = 2,
            Layout_X = 3,
            Layout_Y = 4
        };

		public CompartmentInfo(){

		}

		~CompartmentInfo(){

		}

		public virtual void Dispose(){

		}

        /// <summary>
        /// 区画定義の見出し内容検査
        /// </summary>
        /// <returns></returns>
        public bool CheckFormat()
        {
            //見出し行取得
            string[] title = Rows[0];

            //グループと違い、前半５項目のみ一致している必要がある、それ以外は自由
            if (title.Length < COMPARTMENT_DATA_COLUMN.Length)
            {
                return false;
            }
            for (int i = 0; i < COMPARTMENT_DATA_COLUMN.Length;i++)
            {
                if (title[i] != COMPARTMENT_DATA_COLUMN[i])
                {
                    return false;
                }
            }
            return true;
        }
    }//end Compartment


}//end namespace SWESTAttendeeAllocator