///////////////////////////////////////////////////////////
//  EGroupType.cs
//  Implementation of the Class EGroupType
//  Generated by Enterprise Architect
//  Created on:      2014/08/05 9:05:17
//  Original author: shiba
///////////////////////////////////////////////////////////




namespace AttendeeAllocator
{
	public enum EGroupType : int {

		/// <summary>
		/// Ç®àÍêlól
		/// </summary>
		alone,
		/// <summary>
		/// îrëºÇ∑ÇÈ
		/// </summary>
		exclucive,
		/// <summary>
		/// èWçáÇ≥ÇπÇÈ
		/// </summary>
		gather,
		/// <summary>
		/// ï™éUÇ≥ÇπÇÈ
		/// </summary>
		scattering

	}//end EGroupType

}//end namespace SWESTAttendeeAllocator