///////////////////////////////////////////////////////////
//  Group.cs
//  Implementation of the Class Group
//  Generated by Enterprise Architect
//  Created on:      2014/08/05 9:05:17
//  Original author: shiba
///////////////////////////////////////////////////////////



using System;
using System.Collections.Generic;
namespace AttendeeAllocator
{
    [Serializable]
    public class GroupInfo : CsvData
    {
        /// <summary>
        /// グループ項目定義
        /// </summary>
        string[] GROUP_DATA_COLUMN = new string[]{"名称","排他","集合","分散","除外","優先度"};
        public enum COLUM_POS
        {
            Name = 0,
            Exclusive = 1,
            Gather = 2,
            Scatter = 3,
            Exclude = 4,
            Priority = 5
        };



		public GroupInfo(){

		}

		~GroupInfo(){

		}

		public virtual void Dispose(){

		}

        //------------------------
        //Method
        //------------------------

        /// <summary>
        /// 規定の形式か検査する
        /// </summary>
        /// <returns>結果(OK : true,NG : false)</returns>
        public bool CheckFormat()
        {
            //見出し行取得
            string[] title = Rows[0];
            
            if( title.Length != GROUP_DATA_COLUMN.Length){
                return false;
            }
            int i=0;
            foreach (string word in title)
            {
                if (word != GROUP_DATA_COLUMN[i++])
                {
                    return false;
                }
            }
            return true;

        }

        //------------------------
        //Properties
        //------------------------



        /// <summary>
        /// グループを名前で検索
        /// </summary>
        /// <param name="name">グループ名</param>
        /// <returns>存在する場合：グループ定義一行分、存在しない場合 null</returns>
        public string[] FindGroupByName(string name)
        {
            string[] result = null;

            for (int i = 1; i < _rows.Count; i++ )
            {
                string[] row = _rows[i];
                if( row[(int)COLUM_POS.Name] == name){
                    result = row;
                    break;
                }
            }
            return result;
        }
    }//end Group

}//end namespace SWESTAttendeeAllocator