///////////////////////////////////////////////////////////
//  parser.cs
//  Implementation of the Class parser
//  Generated by Enterprise Architect
//  Created on:      2014/08/05 9:05:17
//  Original author: shiba
///////////////////////////////////////////////////////////




namespace AttendeeAllocator
{
	public class parser {

		public parser(){

		}

		~parser(){

		}

		public virtual void Dispose(){

		}

	}//end parser

}//end namespace SWESTAttendeeAllocator